version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo_adoptme
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_adoptme
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data:

